backend:
  name: github
  repo: iMoMoseat-Collab/my-first-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "announcements"
    label: "ประกาศวันหยุด"
    delete: false
    editor:
      preview: false
    files:
      - file: "_data/announcement.json"
        label: "ข้อความประกาศบนแถบสีทอง"
        name: "announcement"
        fields:
          - {label: "ข้อความประกาศ", name: "text", widget: "string"}
